### ISSUE TITLE
Try to run but no template found exception

### ISSUE THREAD

**Issue by didlawowo** [cs91chris/flask_autocrud#3]
py37\lib\site-packages\jinja2\environment.py", line 907, in select_template

message=u"Tried to select from an empty list " u"of templates."

**Comment by cs91chris** [comment]
Hi,
I cannot reproduce your issue, can you please post packages version (with dependencies), what command you are used and full error log?

**Comment by didlawowo** [comment]
> 
dispatcher 'None' not exists. Use one of dict_keys(['default', 'subdomain', 'urlprefix'])
Startin App in mode staging
 * Serving Flask app "app" (lazy loading)
 * Environment: staging
 * Debug mode: on
 * Restarting with stat
app initialized
Run with staging config
C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_sqlalchemy\__init__.py:835: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disab
led by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
C:\Users\PCDT09181\programme\py37\lib\site-packages\sqlalchemy\orm\relationships.py:2154: SAWarning: On Validation.user, 'passive_deletes' is normally configured on one-to-many, one-t
o-one, many-to-many relationships only.
  "relationships only." % self
C:\Users\PCDT09181\programme\py37\lib\site-packages\sqlalchemy\orm\relationships.py:2154: SAWarning: On Application.config, 'passive_deletes' is normally configured on one-to-many, on
e-to-one, many-to-many relationships only.
  "relationships only." % self
Database init finished
Route and API OK
Update user admin with admin role
Update admin user OK
Bootstrap finished
dispatcher 'None' not exists. Use one of dict_keys(['default', 'subdomain', 'urlprefix'])
Startin App in mode staging
 * Debugger is active!
 * Debugger PIN: 126-323-383
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\response_builder.py", line 189, in wrapper
    return self.build_response(builder, fun(*args, **kwargs))
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\response_builder.py", line 86, in build_response
    builder.build(data, **kwargs)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\builders\builder.py", line 81, in build
    self._data = self._build(data, **kwargs)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\builders\html.py", line 34, in _build
    **kwargs
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\jinja2\environment.py", line 933, in get_or_select_template
    return self.select_template(template_name_or_list, parent, globals)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\jinja2\environment.py", line 907, in select_template
    message=u"Tried to select from an empty list " u"of templates."
jinja2.exceptions.TemplatesNotFound: Tried to select from an empty list of templates.

127.0.0.1 - - [18/May/2020 14:06:16] "?[35m?[1mGET /resources HTTP/1.1?[0m" 500 -
Traceback (most recent call last):
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\response_builder.py", line 189, in wrapper
    return self.build_response(builder, fun(*args, **kwargs))
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\response_builder.py", line 86, in build_response
    builder.build(data, **kwargs)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\builders\builder.py", line 81, in build
    self._data = self._build(data, **kwargs)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\builders\html.py", line 34, in _build
    **kwargs
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\jinja2\environment.py", line 933, in get_or_select_template
    return self.select_template(template_name_or_list, parent, globals)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\jinja2\environment.py", line 907, in select_template
    message=u"Tried to select from an empty list " u"of templates."
jinja2.exceptions.TemplatesNotFound: Tried to select from an empty list of templates.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\app.py", line 1822, in handle_user_exception
    return handler(e)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_errors_handler\handler.py", line 111, in _api_handler
    resp = self._response(lambda: ex.prepare_response())()
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\response_builder.py", line 189, in wrapper
    return self.build_response(builder, fun(*args, **kwargs))
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\response_builder.py", line 86, in build_response
    builder.build(data, **kwargs)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\builders\builder.py", line 81, in build
    self._data = self._build(data, **kwargs)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask_response_builder\builders\html.py", line 34, in _build
    **kwargs
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\jinja2\environment.py", line 933, in get_or_select_template
    return self.select_template(template_name_or_list, parent, globals)
  File "C:\Users\PCDT09181\programme\py37\lib\site-packages\jinja2\environment.py", line 907, in select_template
    message=u"Tried to select from an empty list " u"of templates."
jinja2.exceptions.TemplatesNotFound: Tried to select from an empty list of templates.
127.0.0.1 - - [18/May/2020 14:06:16] "?[37mGET /resources?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1?[0m" 200 -
127.0.0.1 - - [18/May/2020 14:06:16] "?[37mGET /resources?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1?[0m" 200 -
127.0.0.1 - - [18/May/2020 14:06:16] "?[37mGET /resources?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1?[0m" 200 -
127.0.0.1 - - [18/May/2020 14:06:17] "?[37mGET /resources?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1?[0m" 200 -

jinja2.exceptions.TemplatesNotFound

jinja2.exceptions.TemplatesNotFound: Tried to select from an empty list of templates.

**Comment by didlawowo** [comment]
`>pip freeze
alembic==1.4.2
aniso8601==4.1.0
ansible-vault==1.2.0
awscli==1.18.49
bcrypt==3.1.7
beautifulsoup4==4.9.0
blinker==1.4
boto3==1.12.47
botocore==1.15.49
bs4==0.0.1
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.2
colander==1.7.0
colorama==0.4.3
cryptography==2.9.2
dateutils==0.6.8
dicttoxml==1.7.4
docutils==0.15.2
Flask==1.1.2
Flask-AutoCRUD==2.1.2
Flask-Bcrypt==0.7.1
Flask-ErrorsHandler==3.0.1
Flask-JWT==0.3.2
Flask-JWT-Extended==3.24.1
Flask-Mail==0.9.1
Flask-Migrate==2.5.3
Flask-ResponseBuilder==2.0.8
Flask-RESTful==0.3.7
Flask-Script==2.0.6
Flask-SQLAlchemy==2.4.1
gitdb2==2.0.5
GitPython==2.1.11
idna==2.9
iso8601==0.1.12
itsdangerous==1.1.0
Jinja2==2.11.2
jmespath==0.9.5
Mako==1.1.2
MarkupSafe==1.1.1
psycopg2-binary==2.8.5
pyasn1==0.4.8
pycparser==2.20
PyJWT==1.4.2
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2020.1
PyYAML==5.3.1
requests==2.23.0
rsa==3.4.2
s3transfer==0.3.3
six==1.14.0
smmap2==2.0.5
soupsieve==2.0
SQLAlchemy==1.3.16
sqlalchemy-filters==0.11.0
translationstring==1.3
urllib3==1.25.9
Werkzeug==1.0.1
xmltodict==0.12.0

`

**Comment by cs91chris** [comment]
Hi,
first of all ignore this message _"dispatcher 'None' not exists. Use one of dict_keys(['default', 'subdomain', 'urlprefix'])"_, it is an output of Flask-ErrorsHandler, but it cause no issue, I will remove it in the next release.

This _"jinja2.exceptions.TemplatesNotFound"_ happens because you called an API from the browser. In this case Flask-ResponseBuilder is based on the Accept header and tries to generate an html page of which there is no template. To get around this problem you need to add in configuration: `RB_HTML_DEFAULT_TEMPLATE`.

As an example of template look here: [https://github.com/cs91chris/flask_response_builder/blob/master/tests/templates/response.html](https://github.com/cs91chris/flask_response_builder/blob/master/tests/templates/response.html)

**Comment by didlawowo** [comment]
thx for your answer, i try to understand cause i'm not familiar with this frameworks.

do i need a directory template with this file in particulary ? 
could you describe what does mean to add RB... in configuration ? in app.config ? 

my project,don't use flask template, because, i'm doing my front with vue js

thx for your answer :)

**Comment by cs91chris** [comment]
You need the template file only if you want an html page in response, for example in case you call the api with a browserotherwise if you want only api rest with json response do not worry about that and call your apis with vue.
See [https://github.com/cs91chris/flask_response_builder](https://github.com/cs91chris/flask_response_builder) for the behavior of responses.

For template configuration: `app.config['RB_HTML_DEFAULT_TEMPLATE'] = 'template.html'`

Finally, you can force the apis to produce only json with: `app.config['RB_DEFAULT_ACCEPTABLE_MIMETYPES'] = ['application/json']`

**Comment by didlawowo** [comment]
thx for your answer but i'm sorry it doesn't work and i think i don't really understand how does it works,
for me, i thought i just need to add autocrud, and start app to have the "swagger ui" and the API available ? and not...


i have add the template dir and file response.html

add this config

    app.config['AUTOCRUD_METADATA_ENABLED'] = True
    app.config['RB_HTML_DEFAULT_TEMPLATE'] = 'response.html'
 
    AutoCrud(app, db)

but now on /resources

jinja2.exceptions.UndefinedError

jinja2.exceptions.UndefinedError: dict object has no element 0
File "C:\Users\PCDT09181\Documents\gits\fid-forward\app\templates\response.html", line 22, in top-level template code

{% for k, v in data[0].items() %}

**Comment by cs91chris** [comment]
I am sorry, but there are no automatic swagger ui. Yes there are automatic api try with curl, postman or whatever and you will see a json response, maybe you should try with the suggestions of my last comment.

The error is related to the template and you should fix it yourself because it is not part of the package. In addition the response as html is an optional and in rare case is needed, and you not need it because you want send a json to you vuejs app.

**Comment by didlawowo** [comment]
ok thx for your answer, now i understand what it's really.
so if i have a class application in my SQL model, i should find some /resources/application api ? 

i have seen you have improve your code and documentation and thx for it,
maybe a little short example should be usefull in the readme.
